CREATE TABLE IF NOT EXISTS military_power (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    country_code VARCHAR(3) NOT NULL UNIQUE,
    country_name VARCHAR(100) NOT NULL,
    flag_emoji VARCHAR(10),
    rank INTEGER NOT NULL,
    power_index DECIMAL(6,4) NOT NULL,
    active_personnel INTEGER DEFAULT 0,
    reserve_personnel INTEGER DEFAULT 0,
    paramilitary INTEGER DEFAULT 0,
    tanks INTEGER DEFAULT 0,
    armored_vehicles INTEGER DEFAULT 0,
    artillery INTEGER DEFAULT 0,
    rocket_launchers INTEGER DEFAULT 0,
    total_aircraft INTEGER DEFAULT 0,
    fighter_jets INTEGER DEFAULT 0,
    attack_helicopters INTEGER DEFAULT 0,
    transport_aircraft INTEGER DEFAULT 0,
    naval_vessels INTEGER DEFAULT 0,
    aircraft_carriers INTEGER DEFAULT 0,
    submarines INTEGER DEFAULT 0,
    destroyers INTEGER DEFAULT 0,
    frigates INTEGER DEFAULT 0,
    defense_budget DECIMAL(14,2) DEFAULT 0,
    oil_production INTEGER DEFAULT 0,
    airports INTEGER DEFAULT 0,
    ports INTEGER DEFAULT 0,
    nuclear_capable BOOLEAN DEFAULT FALSE,
    alliances VARCHAR(200),
    lat DECIMAL(9,6),
    lng DECIMAL(9,6),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_military_rank ON military_power(rank);
CREATE INDEX idx_military_country ON military_power(country_code);
